package videoLib.view;

import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Toolkit;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

import org.omg.CORBA.TCKind;

public class TandC extends JFrame{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private JPanel contentPane;
	private String tandc = "\t\t\t*TERMS & CONDITIONS* \n\n\n\t"
			+ "\t**** MemberID is autogenerated.****\n\t****Kepp yor ID and Password for further login.****\n\n\t"
			+ "1)Register yourself to search for videos in the library. \n\n\t"
			+ "2)Contact the admin to rent a video CD or return it.\n\n\t"
			+ "3)Renting movie upto 3 days will cost Rupees 50.\n\n\t"
			+ "4)More than 3 days Rupees 10 per day will be incremented as fine.";


	/**
	 * Create the frame.
	 */
	public TandC() {
		setResizable(false);
		setTitle("ABC Library - Terms and Conditions");
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		setIconImage(Toolkit.getDefaultToolkit().getImage(TandC.class.getResource("/resources/images/icon.png")));
		setBounds(100, 100, 612, 383);
		contentPane = new JPanel();
		contentPane.setForeground(Color.BLACK);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(10, 86, 586, 240);
		contentPane.add(scrollPane);
		
		JTextArea textArea = new JTextArea();
		textArea.setWrapStyleWord(true);
		textArea.setLineWrap(true);
		textArea.setEditable(false);
		scrollPane.setColumnHeaderView(textArea);
		textArea.setText(tandc);
		
		JLabel lblTermsAndConditions = new JLabel("Terms and Conditions");
		lblTermsAndConditions.setForeground(Color.BLACK);
		lblTermsAndConditions.setFont(new Font("Tahoma", Font.BOLD, 25));
		lblTermsAndConditions.setHorizontalAlignment(SwingConstants.CENTER);
		lblTermsAndConditions.setBounds(10, 25, 541, 50);
		contentPane.add(lblTermsAndConditions);
		
	}


}
